---
# Create virtual environment, copy project and make a service
- name: include vars
  include_vars: venv-vars.yml

- name: Install git
  apt:
    name: git
    state: present

- name: Clone project from github
  git:
    repo: "{{ gitrepo }}"
    dest: /tmp/homework

- name: Create pyproject directory
  file:
    path: /var/pyproject
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

# copy pyproject files from cloned repository,
# because it is not separate repo, but part of homework repository
# (three tasks below)
- name: Set permission on script file
  file:
    path: /tmp/homework/4-task/pyproject/copyproject.sh
    mode: '0755' 

- name: Copy pyproject files from cloned repository by script
  command: /tmp/homework/4-task/pyproject/copyproject.sh

- name: Set permissions and ownership on pyproject files
  file:
    path: '/var/pyproject/{{ item }}'
    owner: vagrant
    group: vagrant
    mode: '0755'
  with_items:
    - jsonproc.py
    - wsgi.py

- name: Create python venv and install here wheel, gunicorn, flask, emoji in it
  pip:
    name: "{{ pipapps }}"
    virtualenv: /var/pyproject/pyprojenv
    virtualenv_command: pyvenv
    state: present

- name: Copy pyproject.service
  copy:
    src: pyproject.service
    dest: /etc/systemd/system/pyproject.service

- name: Start service pyproject
  service:
    name: pyproject
    state: started
    enabled: yes
