Vagrant.configure("2") do |config|
#One key to all hosts
  config.ssh.insert_key = false
#Three vagrant hosts configuration
  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "debian/buster64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8081
    vagrant1.vm.network "forwarded_port", guest: 443, host: 4431
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "debian/buster64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8082
    vagrant2.vm.network "forwarded_port", guest: 443, host: 4432
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "debian/buster64"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8083
    vagrant3.vm.network "forwarded_port", guest: 443, host: 4433
  end  
end
