---
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Enable netfilter-persistent service
  service:
    name: netfilter-persistent
    state: started
    enabled: yes

- name: Copy file with iptables rules
  copy:
    src: files/iptables
    dest: /tmp/
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Apply iptables rules
  command: /usr/sbin/iptables-restore iptables
  args:
    chdir: /tmp/

- name: Save iptables rules
  command: /usr/sbin/iptables-save -f /etc/iptables/rules.v4