---
- name: update cache befor pakage install
  apt:
    update_cache: yes

#copy file with iptables rules and apply its
#- include: iptables-cp.yml

#create iptable rules
- include: iptables-create.yml

- include: packages.yml