Vagrant.configure("2") do |config|
#One key to all hosts
  config.ssh.insert_key = false
  config.vm.define "vagrant2" do |minikube|
    minikube.vm.box = "debian/buster64"
    minikube.vm.hostname = "minikube.local"
    minikube.vm.network "private_network", ip: "192.168.50.104", hostname: true
  end
  config.vm.provider "virtualbox" do |minikube|
    minikube.name = "minikube"
    minikube.memory = 2048
    minikube.cpus = 2
  end
end
